### PR TITLE
Added actual trees for Tnx0Vpnx1 and Tnx0Vnx1pnx2

### PR DESCRIPTION
**Pull request by jonpiffle**
The tree files for Tnx0Vpnx1 and Tnx0Vnx1pnx2 were duplicates of Tnx0VPnx1 and Tnx0Vnx1Pnx2.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
Hi! Thanks for the PR. I don't fully understand what changes were made. Did you see the files `Tnx0Vnx1_pnx2.trees` and `Tnx0V_pnx1.trees`. We added the underscores to preserve the original files for `Tnx0Vnx1Pnx2.trees` and `Tnx0VPnx1.trees` for filesystems that are case insensitive. We map from the latter to the former on the fly when matching lexical entries in the syntax file that maps words to tree families.

**Comment by jonpiffle** [comment]
Sorry, should have been more specific. The lowercase/underscore trees you have uploaded are actually just copies of the uppercase ones. See:
[Tnx0Vnx1_pnx2](https://github.com/sfu-natlang/xtag-english-grammar/blob/master/grammar/Tnx0Vnx1_pnx2.trees) and [Tnx0Vnx1Pnx2](https://github.com/sfu-natlang/xtag-english-grammar/blob/master/grammar/Tnx0Vnx1Pnx2.trees)

As you can see in [Tnx0Vnx1_pnx2](https://github.com/sfu-natlang/xtag-english-grammar/blob/master/grammar/Tnx0Vnx1_pnx2.trees) the "P" nodes are still marked as anchors instead of substitution nodes.

**Comment by jonpiffle** [comment]
Maybe I have them backwards; I was assuming "_" was supposed to be the lowercase versions. If "_" was supposed to indicate the uppercase versions, then the currently uploaded files without underscores should be replaced with what I've committed instead.

Either way, in both cases the two files are identical

**Comment by anoopsarkar** [comment]
Uppercase `P` is when the preposition is the anchor and we use `_p` instead of `P`

    syntax/code_families.txt:    6  Tnx0Vnx1Pnx2	      Verb_w_DO_and_prep_complement
    syntax/syntax-coded.flat:    <<INDEX>>accustom<<ENTRY>>accustom<<POS>>V<<ENTRY>>to<<POS>>P<<FAMILY>>Tnx0Vnx1Pnx2<<FEATURES>>#p_acc

Lowercase `p` is when the preposition is substituted in:

    syntax/code_families.txt:    5  Tnx0Vnx1pnx2           Ditransitive_with_PP
    syntax/syntax-coded.flat:<<INDEX>>foist<<ENTRY>>foist<<POS>>V<<FAMILY>>Tnx0Vnx1pnx2

Right now uppercase `P` and `_p` files are identical (as it should be). However, you are right that the lowercase `p` trees with subst nodes are missing right now. Could you please change (if needed) your PR so that the lowercase `p` files using a subst node for the preposition?

A filesystem that is case insensitive like the default HFS+ of macosx will clobber the upper with the lowercase files (or vice versa) so be careful. I think this is what caused the bug in the first place.

**Comment by jonpiffle** [comment]
Ah, I see -- I assumed `_p` referred to lowercase `p` since the lowercase files were missing.

Given the filesystem clobbering, it seems like only one set of case insensitive trees should exist for a given name. So would you prefer:

1. Remove `Tnx0Vnx1Pnx2.trees` and `Tnx0VPnx1.trees` and add `Tnx0Vnx1pnx2.trees` and `Tnx0Vpnx1.trees` (with the upper case trees in the underscore files)

2. Keep the `Tnx0Vnx1Pnx2.trees` and `Tnx0VPnx1.trees` and replace the contents of `Tnx0Vnx1_pnx2.trees` and `Tnx0V_pnx1.trees` with `Tnx0Vnx1pnx2.trees` and `Tnx0Vpnx1.trees`.

The current PR was for (2), but I can change it to (1) if you prefer. It doesn't seem like a good idea to just add the missing lowercase files though, as they will be clobbered.

**Comment by anoopsarkar** [comment]
I prefer option 1 as it matches the syntax files and the assumptions we made in the xtag-nltk python code that reads the grammar and syntax files. Thanks!

**Comment by jonpiffle** [comment]
Okay, this branch now reflects (1). `Tnx0Vnx1Pnx2`.trees and `Tnx0VPnx1.trees` were removed and `Tnx0Vnx1pnx2`.trees and `Tnx0Vpnx1.trees` were added.

**Pull request merged**
